2021-06-22 08:01:02,646 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 8305684ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-22 09:15:56,808 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 653461ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-22 10:44:39,385 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 381686ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-22 13:17:30,690 ERROR 26648 [-/127.0.0.1/-/5ms GET /aboutus] nodejs.AssertionError: Can't find page/about-us/index.nj from /Users/lixiao/Desktop/selfwork/app/view
    at Map.resolve (/Users/lixiao/Desktop/selfwork/node_modules/_egg-view@2.1.3@egg-view/lib/view_manager.js:74:5)
    at async ContextView.[contextView#render] (/Users/lixiao/Desktop/selfwork/node_modules/_egg-view@2.1.3@egg-view/lib/context_view.js:50:22)
    at async HomeController.aboutUs (/Users/lixiao/Desktop/selfwork/app/controller/page/home.js:11:5)
    at async checkToken (/Users/lixiao/Desktop/selfwork/app/middleware/checkToken.js:22:9)
    at async /Users/lixiao/Desktop/selfwork/node_modules/_egg-development@2.7.0@egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/lixiao/Desktop/selfwork/node_modules/_egg-security@2.9.0@egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/lixiao/Desktop/selfwork/node_modules/_egg-security@2.9.0@egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/lixiao/Desktop/selfwork/node_modules/_egg-security@2.9.0@egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/lixiao/Desktop/selfwork/node_modules/_egg-security@2.9.0@egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/lixiao/Desktop/selfwork/node_modules/_koa-session@6.2.0@koa-session/index.js:41:7)
    at async bodyParser (/Users/lixiao/Desktop/selfwork/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:95:5)
    at async /Users/lixiao/Desktop/selfwork/node_modules/_koa-static-cache@5.1.4@koa-static-cache/index.js:73:16
    at async notfound (/Users/lixiao/Desktop/selfwork/node_modules/_egg@2.29.4@egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/lixiao/Desktop/selfwork/node_modules/_egg@2.29.4@egg/app/middleware/meta.js:17:5)
generatedMessage: false
code: "ERR_ASSERTION"
actual: undefined
expected: true
operator: "=="
pid: 26648
hostname: bogon

2021-06-22 15:49:56,579 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 1129706ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-22 17:47:13,780 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 536208ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-22 18:39:03,384 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 2029192ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-22 22:03:09,389 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 12205980ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

2021-06-23 05:40:55,559 ERROR 19200 nodejs.ClusterClientNoResponseError: client no response in 27366142ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/lixiao/Desktop/selfwork/node_modules/_cluster-client@3.0.1@cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
name: "ClusterClientNoResponseError"
pid: 19200
hostname: bogon

